name: m2
script:
  - git clone https://github.com/hurrialice/smk-m2.git
  - cd /home/qing/smk-m2
  - snakemake --config JobIndex=$index
resources:
  cpus-per-task: 1
  mem-per-cpu: 4G
inputs:
  index:
    - 0
    - 1
backend:
  type: TransientGCP
  name: smk-m2-proof
  controller_type: n1-standard-4
  worker_type: n1-standard-1
  controller_disk_size: 10G
  controller_script: >
    # get the data sources
    wget ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/funcotator/funcotator_dataSources.v1.6.20190124s.tar.gz
    && tar xvzf funcotator_dataSources.v1.6.20190124s.tar.gz
    && cd funcotator_dataSources.v1.6.20190124s
    && rm -rf achilles 

  compute_script: >
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b && echo 'export PATH=~/miniconda3/bin:~/.local/bin:$PATH' >> ~/.bashrc
    && source ~/.bashrc && conda install -y matplotlib numpy graphviz pandas && pip install snakemake 
    && wget https://github.com/broadinstitute/gatk/releases/download/4.1.4.0/gatk-4.1.4.0.zip
    && unzip gatk-4.1.4.0.zip && echo 'export PATH=~/gatk-4.1.4.0/.gatk:$PATH' >> ~/.bashrc && source ~/.bashrc
outputs:
  filtered: "*/annot_merged_filtered.vcf"