# # NCI data commons credentials (path)
credential: "credentials/credentials.json"
user_project: "broad-cga-qing-gdac"
gs_keys: "~/auth.json" # must not in shared NFS

# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: "../../drs_test.tsv" # contains 10 samples
all_samples: "/demo-mount/M2_refs/mpaires_update.tsv"

# split intervals into {pieces} and stored at {subintervals}
pieces: 20
subint_dir: "subintervals"

# reference genome
ref: "/demo-mount/M2_refs/Homo_sapiens_assembly19.fasta"
ref_dict: "/demo-mount/M2_refs/Homo_sapiens_assembly19.dict"


# defaults params from best-practice
default_pon: "/demo-mount/M2_refs/Mutect2-exome-panel.vcf"
gnomad: "/demo-mount/M2_refs/af-only-gnomad.raw.sites.b37.vcf"
vfc: "/demo-mount/M2_refs/small_exac_common_3.vcf"
wes_interval_list: "/demo-mount/M2_refs/whole_exome_agilent_1.1_refseq_plus_3_boosters.Homo_sapiens_assembly19.baits.interval_list"

# where I stored the data files for funcotator
onco_folder: "/demo-mount/M2_refs/funco_slim"


# will be in [CLUSTER soon]
scatter_heap_mem: 4
heapmem: 2
